### PR TITLE
Improve local run

### PR DESCRIPTION
**Pull request by shawncao**
use run.sh to run with prebuilt binaries if build is not available for people who just wants to give it a try without building the project.

### CODE REVIEW

**Comment by shawncao** [comment]
@jiaojialin I removed the local-test script based on your feedback. Now run.sh can run up nebula without building the whole project.

**Review by jiaojialin — COMMENTED** [review]
I tried it, but the nebula API node.js was not started by running this run.sh script

**Review by jiaojialin — COMMENTED** [review]
also, could you create another shutdown script ? because when I Ctrl+C to exit, the Node and Server are not killed

**Review by jiaojialin — COMMENTED** [review]
also, tried to kill the NodeServer first, could not kill it by kill command

`
jiao@jiao-mbp:nebula  (improve-local-run)$ ps aux | grep nebula
jiao             33833   0.0  0.0  4408572    816 s003  S+    6:58PM   0:00.00 grep nebula
jiao             31998   0.0  0.0  5637584  14004 s003  S     6:40PM   0:00.40 /Users/jiao/personal/nebula/test/bin/macos/NebulaServer --CLS_CONF /Users/jiao/personal/nebula/src/configs/test.yml
jiao             31995   0.0  0.1  5235828  21840 s003  S     6:40PM   0:00.64 /Users/jiao/personal/nebula/test/bin/macos/NodeServer
jiao@jiao-mbp:nebula  (improve-local-run)$ kill -9 31995
jiao@jiao-mbp:nebula  (improve-local-run)$ E20201127 18:58:23.411401 290721216 NodeClient.cpp:159] RPC failed to localhost: code=14, msg=Socket closed
I20201127 18:58:23.411444 290721216 ConnectionPool.cpp:81] Removing a channel to localhost:9199
I20201127 18:58:28.421701 290721216 ConnectionPool.cpp:64] Creating a channel to localhost:9199
E20201127 18:58:28.425140 290721216 NodeClient.cpp:159] RPC failed to localhost: code=14, msg=Connect Failed
I20201127 18:58:28.425175 290721216 ConnectionPool.cpp:81] Removing a channel to localhost:9199
I20201127 18:58:33.427345 290721216 ConnectionPool.cpp:64] Creating a channel to localhost:9199
E20201127 18:58:33.430317 290721216 NodeClient.cpp:159] RPC failed to localhost: code=14, msg=Connect Failed
I20201127 18:58:33.430349 290721216 ConnectionPool.cpp:81] Removing a channel to localhost:9199
I20201127 18:58:38.444402 290721216 ConnectionPool.cpp:64] Creating a channel to localhost:9199
E20201127 18:58:38.448082 290721216 NodeClient.cpp:159] RPC failed to localhost: code=14, msg=Connect Failed
I20201127 18:58:38.448118 290721216 ConnectionPool.cpp:81] Removing a channel to localhost:9199
I20201127 18:58:38.448130 290721216 ConnectionPool.h:69] Marking this node as bad since it is reseting every 3
W20201127 18:58:38.448141 290721216 NodeManager.h:78] Removing a node as it's marked as bad.
W20201127 18:58:43.455935 290721216 SpecRepo.cpp:345] No nodes to assign nebula specs.
W20201127 18:58:48.461313 290721216 SpecRepo.cpp:345] No nodes to assign nebula specs.
W20201127 18:58:53.470228 290721216 SpecRepo.cpp:345] No nodes to assign nebula specs.
`

**Comment by shawncao** [comment]
`./run.sh down` is supposed to kill all running services. Otherwise it will check if target services are running, skip launching them if found.

what error did you see when you run `./run.sh`?

**Comment by jiaojialin** [comment]
> `./run.sh down` is supposed to kill all running services. Otherwise it will check if target services are running, skip launching them if found.
> 
> what error did you see when you run `./run.sh`?

It was because I did not have yarn installed. Now I installed it, the run.sh was able to run successfully.
However, I noticed it took quite some time for the first time, it is because it needs to load the data? 

`
20201128 22:21:06.348948 378584512 NebulaServer.cpp:515] Loading nebula cluster config: /Users/jiao/personal/nebula/src/configs/test.yml
[3/4] 🔗  Linking dependencies...
[-------------------------------------------------------------------------------------------------------------------------------------------------] 0/503E20201128 22:21:08.159276 378584512 S3.cpp:118] Error reading key: meta/version. Unable to parse ExceptionName: InvalidRequest Message: Request specific response headers cannot be used for anonymous GET requests. with address : 52.219.56.58 with address : 52.219.56.58
[4/4] 🔨  Building fresh packages...
[1/2] ⠁ grpc
I20201128 22:21:13.376773 378584512 SpecRepo.cpp:297] Updating 1 specs: brandnew=1, renew=0, removed=18446744073709551615, count=1
I20201128 22:21:13.377245 378584512 ConnectionPool.cpp:64] Creating a channel to localhost:9199
[1/2] ⠈ grpc
[1/2] ⠁ grpc
[1/2] ⠂ grpc
I20201128 22:21:14.411681 99356672 BlockLoader.cpp:153] Loaded test blocks: 4 using seed=1606630874
[1/2] ⠄ grpc
I20201128 22:21:14.487510 99356672 BlockLoader.cpp:153] Loaded test blocks: 4 using seed=1606630874
[1/2] ⡀ grpc
[1/2] ⢀ grpc
[1/2] ⠠ grpc
[1/2] ⠁ grpc
✨  Done in 168.33s.
`

**Review by jiaojialin — APPROVED** [review]
tested and it run successfully. LGTM!

**Comment by shawncao** [comment]
yes, it takes some time for cluster to warm up, but should be within 15 seconds. Startup time may be related to node module installation too.

**Pull request merged**
