### PR TITLE
Update slogan for Nebula

### PR DESCRIPTION
**Pull request by jiaojialin**
Change slogan/tagline from "A distributed block-based data storage and compute engine" to "Faster Interactive Big Data Analytics"

### CODE REVIEW

**Comment by shawncao** [comment]
Should we add keyword "distributed" in it?

**Comment by jiaojialin** [comment]
> Should we add keyword "distributed" in it?

let me explain why I come up with this:

-  the "big data" in "big data analytics" already implies a few things:   (1) large scale and scalability - everybody nowadays know big data == large scale  (2)  what do you think about distributed?  could you do big data without distributed system? of course not!
-  faster: of course, that's one probably biggest selling point of Nebua
- easier: this includes a few things as well:  (1) Nebula support many different data sources - versatile and ready to use (2) user-friendly API/SDK  (3) easy to install and setup (4) a lot of other user-friendly features
- I believe speed and easy to use are the two most important attraction Nebula has, as to other including secure (we have not implemented a lot of unique features for security yet, right? also, I believe security and reliability and a lot of features are basic and every big data analytics system/framework should have,  it does not need to highlined

Also, I think we want a easy to remember and loud and clear slogan/tagline, we don't need to put everything in it,   it will become too common and not special any more if you put everything in it

**Comment by shawncao** [comment]
Well explained! Makes sense.

Should we highlight nebula is an end to end product with native web UI for user?

Nebula is designed with 0 dependencies, I guess it's one reason for 'easier'?

**Comment by jiaojialin** [comment]
> Should we highlight nebula is an end to end product with native web UI for user?

We could high-line a lot of great features in our documentations,  but tagline/slogan are not supposed to include everything.   That's how we leave more room for people to imagine and more room for Nebula creators to grow it.  How could you put the meaning of "an end to end product with native web UI for user" in a simple slogan?  I think "easier" includes that already.   We don't have to think the slogan is final, we could always update it

**Review by shawncao — APPROVED** [review]
Thanks @jiaojialin

**Comment by jiaojialin** [comment]
@shawncao 
Actually, here are the list of lines I had thought about:

Nebula -  distributed OLAP for big data
fast big data analytics
Real-time big data analytics
fast, scalable, reliable, real-time, and user friendly
fast and versatile big data analytics
fast and versatile big data analytics made easy
faster, easier big data analytics 
Faster big data analytics for every use case
Fast big data analytics for every use case
Fast Big Data Analytics Made Easy
Where big data analytics becomes faster and easier
Fast big data analytics Made Easy
Faster big data analytics
Fast, versatile and user-friendly big data analytics
Big Data Analytics, Faster and Easier
Big Data Analytics, Faster, Easier, Prettier


any thought?

**Comment by jiaojialin** [comment]
anyway, the original description "A distributed block-based data storage and compute engine" is (1) too technical (2) does not highlight the awesomeness of Nebula
we could probably use such technical abstract in paper, or technical forum
but definitively not a good line to use in nebula.bz or customer facing materials

**Comment by shawncao** [comment]
how about "Nebula - simple, fast and unlimited interactive data analytics engine"?

**Comment by jiaojialin** [comment]
"interactive" is something new, worth considering, and maybe quite unique feature of Nebula
"unlimited" is ambiguous, what do you mean by "unlimited" here?
One concern about "Simple" is that it might relate to some thinking about it is not advanced ?

probably we could do

"**Nebula - Fast, User-friendly and Interactive Big Data Analytics**"

I think putting "engine" is unnecessary and also limiting the scope of it
we are doing "Big Data Analytics", including but not limited to the engine itself, right? we could have cloud-base service
 

> how about "Nebula - simple, fast and unlimited interactive data analytics engine"?

**Pull request merged**
